# Generated by Django 5.2.3 on 2026-03-12 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_reserva_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='comida',
            name='tipo',
            field=models.CharField(choices=[('comida', 'Comida'), ('vino', 'Vino')], default='comida', max_length=20),
        ),
    ]
