# Generated by Django 6.0.3 on 2026-04-29 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_zonadelivery_alter_comida_id_alter_itempedido_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='zona',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
